# Generated by Django 3.1.7 on 2021-06-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210617_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non-binary', 'Non-Binary'), ('transgender', 'Transgender')], max_length=20),
        ),
    ]
