# Generated by Django 3.1.7 on 2021-06-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210617_0745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='passenger',
            table='passengers',
        ),
    ]
