# Generated by Django 3.1.7 on 2021-06-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210620_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='parentsOrChildrenAboard',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='siblingsOrSpousesAboard',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
