# Generated by Django 3.1.7 on 2021-06-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210620_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passengerClass',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Class'), (2, 'Second Class'), (3, 'Third Class')]),
        ),
    ]
